config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions",
      registrations: "users/registrations"}

  resources :users, only: [:show]
  resources :groups do
    member do
      get 'invitations', to: "invitations#show"
    end
    member do
      post 'invitations', to: "invitations#create"
    end
  end

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  #has_many :users
  belongs_to :user
  has_many :invitations
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show

  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :amount, :currency, :period, :period_type, :start_date)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="container">
  <header>
    <title>Start your Tontine</title>
    <%= stylesheet_link_tag "application" %>
  </header>
  <%= simple_form_for(@group) do |f| %>
  <% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

    <ul>
      <% @group.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :amount %>
  <%= f.input :currency %>
  <%= f.input :period %>
  <%= f.input :period_type %>
  <%= f.input :start_date %>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Period</th>
      <th>Period type</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.amount %></td>
        <td><%= group.currency %></td>
        <td><%= group.period %></td>
        <td><%= group.period_type %></td>
        <td><%= group.start_date %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/invite.html.erb
<form class="form-inline" action="<%= invitations_group_path %>" method="post">
  <div id="invite-1">
    <div class="row no gutter">
      <div class= "col-sm-12">
        <label for="exampleInputName2">Name</label>
        <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
        <label for="exampleInputEmail2">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
      </div>
    </div>
  </div>
  <div id="invite-2">
    <div class="row no gutter">
      <div class= "col-sm-12">
        <label for="exampleInputName2">Name</label>
        <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
        <label for="exampleInputEmail2">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
      </div>
    </div>
  </div>
  <div id="invite-3">
    <div class="row no gutter">
      <div class="col-sm-12">
        <label for="exampleInputName2">Name</label>
        <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
        <label for="exampleInputEmail2">Email</label>
        <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
      </div>
    </div>
  </div>
  <div class="wrapper">
    <button type="submit" class="btn btn-default">Send invitation</button>
  </div>
</form>

app/views/groups/new.html.erb
<div class="container">
<h1>New Group</h1>
<%= render 'form' %>
<%= link_to 'Back', groups_path %>
</div>

app/views/groups/show.html.erb
  <div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-md-12">
      <div class= "container">
        <p>
          <div class="header">
            <h1>
              <div id="name">
                <%= @group.name %>
              </div>
              <div>

              </div>
            </h1>
            <% if @group.user %>
            <h2>created by <%= @group.user.email %></h2>
            <% end %>
          </div>
        </div>
      </p>
    </div>
  </div>
</div>
<p>
  <div class="group-details container">
    <div class="row">
      <div class="col-md-8" align="right">
        <p><%=image_tag "Rama_pic.jpg", class: "img-circle"%>
          <%=image_tag "keith_dent_profile.jpg", class: "img-circle"%>
          <%=image_tag "Andy-Kawa-web1-140x140.jpg", class: "img-circle"%></p>
          <p><%=image_tag "image_MBA_candidate.jpeg", class: "img-circle"%>
            <%=image_tag "blackwomanradio.jpeg", class: "img-circle"%>
            <%=image_tag "Syreeta-McFadden.jpg", class: "img-circle"%></p>
          </div>
          <div class="invitation controller">
            <div class="row">
            <div class="col-md-8" align="right">
          <tbody>
            <% @group.invitations.each do |user| %>
              <tr>
                <th><%= user.name %></th>
              </tr>
            <% end %>
          </tbody>
        </div>
        </div>
          <div class="col-md-4">
            <div id= "description"</div>
              <%= @group.description %>
            </p>
            <p>
              <span id= "amount">
                <%= @group.amount %>
              </span>
              <span id= "currency">
               <%= @group.currency %>
             </span>
           </p>
           <p>
            <span id= "period">
              <%= @group.period %>
            </span>
            <span id= "period type">
              <%= @group.period_type %>
            </span>
          </p>
          <p>
            <div class= "Start date"></div>
            <%= @group.start_date %>
          </p>
          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
              <span class="sr-only">20% Complete (success)</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_group_path(@group) %>
  <%= link_to 'Invitations', invitations_group_path(@group) %>
</div>