config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions",
      registrations: "users/registrations"}

  resources :users, only: [:show]
  resources :groups do
    member do
      get 'invitations', to: "invitations#show"
    end
    member do
      post 'invitations', to: "invitations#create"
    end
  end

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    User.class
  end
end

app/views/welcome/index.html.erb
  <!-- Header -->
    <header>
      <div class="container" >
        <div= "row">
        <div class="col-md-8">
          <div class="intro-text tagline">
              <div class="intro-lead-in"> Save money with your friends</div>
              <div class="intro-heading">
                <p>Tontine is a peer-to-peer savings platform. We connect people in the same social network by allowing them to create a simple online savings circles for mutual assistance. Do you want to start or join a tontine?
                </p>
                </div>
              <a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="intro-text signup-box">

          <h2>Sign up</h2>

          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.input :email, required: true, autofocus: true %>
              <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @validatable) %>
              <%= f.input :password_confirmation, required: true %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Sign up" %>
            </div>

          <% end %>
          <%= render "users/shared/links" %>
            </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      </header>

    <!-- Services Section -->
      <section id="HowItWorks">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">How It Works</h2>
                    <p>
                    <h3 class="section-subheading text-muted">Start your tontine in 4 easy steps</h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-3">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-file-text-o fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">1. Create An Account</h4>
                    <p class="text-muted"> To create your account, enter your email, password and password confirmation. Once that's done, we'll send you an email confirmation. Please make sure to click on the link to activate your account.</p>
                </div>
                <div class="col-md-3">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-users fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">2. Start a Saving Group</h4>
                    <p class="text-muted">You can start saving with your friends at anytime. All you need is to agree on an amount and decide how long you want to save for. </p>
                </div>
                <div class="col-md-3">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">3.Invite Your Friends</h4>
                    <p class="text-muted"> It's simple an easy to invite your friends through Facebook, email and by sms.</p>
                </div>
                <div class="col-md-3">
                  <span class="fa-stack fa-4x">
                      <i class="fa fa-circle fa-stack-2x text-primary"></i>
                      <i class="fa fa-area-chart fa-stack-1x fa-inverse"></i>
                  </span>
                  <h4 class="service-heading">4. Manage Your Savings</h4>
                  <p class="text-muted"> Now that your friends have successfully joined your group, you can start managing your savings history, building your rating, connect with your group and banks.</p>
                </div>
            </div>
        </div>
    </section>
    <!-- About Us Section -->
    <section id="AboutUs" class="bg-light-gray">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class = "text-center">
            <h2 class="section-heading">About Us</h2>
            <h3 class="section-subheading text-muted"> Tontine is improving the way people have access to finance and manage their savings.</h3></div>
            <p>
            People have saved money this way for centuries.
            Tontine is rooted informal financial institutions found in developing countries. We use technology to enable friends to pool and manage their funds together.
            </p>
            <p>
            More than a loan, an investment in your peers.
            Tontine is an excellent way to help your peers bring their projects to life.
            </p>
          </div>
        </div>
    </section>

    <!-- Testimonials Section -->

    <section id="Testimonials">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Testimonials</h2>
                    <h3 class="section-subheading">
                      <p>Tontine is community of people working together to improve financial inclusion.</p>
                      <p>More than a saving group, is an investment in the future.</p>
                    </h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="users">
                      <div class="text-center"> <%= image_tag "keith_dent_profile.jpg", class: "img-circle" %>
                        <h4>George Nzita</h4>
                      </div>
                        <div class= "seethrough-box">
                        Treasurer at MRM Savings group<br>saved 2,100$ with 5 people during 6 months</br>
                        </div>
                          "Tontine allows me to easily stay in touch with all our members, send sms reminders for payments and meetings. Every member of our group is now able to build their financial history on Tontine and connect with banks."
                        </p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="user">
                      <div class="text-center">
                      <%=image_tag "Rama_pic.jpg", class: "img-circle"%>
                        <h4>Elisabeth Kabongo</h4>
                      </div>
                      <div class= "seethrough-box">
                        Small Business Owner<br>saved 14,000$ with 12 people during 12 months
                      </div>
                        <p>
                          "Tontine has made it possible for me to save and invest 1,200$ in my new business. I was able to save more and get a bigger loan from my friends."
                        </p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="user">
                      <div class="text-center">
                      <%=image_tag "blackwomanradio.jpeg", class: "img-circle"%>
                        <h4>Marie Labarre</h4>
                      </div>
                       <div class= "seethrough-box">
                        Student<br>Saved 720$ with 6 people during 6 months</br><br></br>
                      </div>
                        <p>
                          "Thanks to my Tontine I was able to save 720$ for my tuition fees and university expenses. Tontine is an excellent way for young people to invest in thier future."
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted">Start saving with your friends.</p>
                </div>
            </div>
        </div>
    </section>
    <section id="KeepInTouch">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Keep In Touch</h2>
                    <h3 class="section-subheading text-muted">Have any questions? We're here to help.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Your Message *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <button type="submit" class="btn btn-xl">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Tontine 2015</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>